spring:
  datasource:
    druid:
      # 数据库访问配置, 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hibernate?serverTimezone=UTC
      username: root
      password: 123456 # 此处修改为用户对应的密码
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml  #指定mapper 文件的位置
  type-aliases-package: com.yaoge.springbootMybatis.pojo  #为实体类 所在的包 指定别名
  config-location:  classpath:mybatis-config.xml  # 可以用来指定 mybatis全局配置文件