spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hibernate?serverTimezone=UTC
    username: root
    password: 123456 # 此
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml  #指定mapper 文件的位置
  type-aliases-package: com.yaoge.bootmybatismultidatasource.pojo #为实体类 所在的包 指定别名
#  config-location:  # 可以用来指定 mybatis全局配置文件